---
- name: Install and configure Nginx
  hosts: all
  become: yes
  tasks:
    - name: Disable host key checking
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: Start Nginx
      service:
        name: nginx
        state: started
