---
- name: Installing Docker and Updating apt packages
  hosts: webserver
  become: yes  # This is required to execute commands with sudo privileges

  tasks:
    - name: Check if Docker is installed
      command: docker -v
      ignore_errors: yes
      register: docker_version

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
      when: docker_version.rc != 0

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    # Add more tasks as needed for specific packages or operations

