---
- name: Configure VM
  hosts: webserver
  become: true
  vars:
    ansible_ssh_private_key_file: /bitnami/jenkins/home/workspace/create_infra_VM_using_terraform_jenkins/private_key.pem  
  tasks:  
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: true
