---
- hosts: all
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    
  tasks:
    - name: SSH into the host      
      command: ssh  -i /bitnami/jenkins/home/.ssh/cicd_jenkins_rsa  jenkins@{{ inventory_hostname }} 
      
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: true
