---
- name: Pull Docker image from GCR and run container
  hosts: webserver
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes
      
      - name: Authenticate with Docker
      command: >
        docker login us-central1-docker.pkg.dev
        -u _json_key
        -p "{{ lookup('file', '/home/shandba90/jenkins-gce.json') }}"
      become: yes
      
    - name: Pull Docker image
      docker_image:
        name: us-central1-docker.pkg.dev/devops-project-1-419603/docker-images2/oracle/database:21.3.0-se2
        state: present
