---
- name: Configure VM
  hosts: your_vm_hostname_or_group
  become: true
  vars:
    ansible_ssh_private_key_file: /path/to/private_key.pem  
  tasks:  
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: true
