---
- name: Pull Docker image from GCR and run container
  hosts: webserver
  gather_facts: false
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Retrieve metadata value
      shell: "curl -H 'Metadata-Flavor: Google' http://metadata/computeMetadata/v1/instance/attributes/json_key"
      register: metadata_result
      changed_when: false
 
    - name: Authenticate with Docker
      shell: >
        echo "{{ metadata_result.stdout }}" | base64 -d > /home/shandba90/jenkins-gce.json && \
        docker login us-central1-docker.pkg.dev -u _json_key -p "$(cat /home/shandba90/jenkins-gce.json)"
      become: yes

    - name: Pull Docker image
      docker_image:
        name: us-central1-docker.pkg.dev/devops-project-1-419603/docker-images2/oracle/database:21.3.0-se2
        source: pull 
        state: present
        
    - name: Run Docker container  # Ensure this line is properly aligned
      docker_container:
        name: my_container
        image: us-central1-docker.pkg.dev/devops-project-1-419603/docker-images2/oracle/database:21.3.0-se2
        state: started 
      
    - name: Copy script file
      copy:
        src: /home/shandba90/script1.sh  # Local path to your script file
        dest: /home/shandba90/script1.sh  # Destination path on the new VM
        mode: "0755"  # Adjust permissions as needed    

    - name: "Copy the SQL file to the container and execute it "
      shell: "{{ item }}"
      register: command_output
      with_items:
        - sudo docker cp /home/shandba90/script1.sh my_container:/tmp/
        - sudo docker exec -it my_container bash -c "/tmp/script1.sh > /tmp/script1.csv"
        - sudo docker exec -it my_container bash -c "cat /tmp/script1.csv"
        - sudo docker exec -it my_container bash -c /tmp/script1.sh > /tmp/script1.csv   
        - chmod 755 /tmp/script1.csv
        - cat /tmp/script1.csv

    - name: "Display command output"
      debug:
        msg: "{{ item.stdout }}"
      with_items: "{{ command_output.results }}" 

    - name: Fetch files
      fetch:
        src: /tmp/script1.csv
        dest: /tmp/
        flat: yes  

    - name: "Display SQL*Plus output"
      debug:        
        msg: "{{ lookup('file', '/tmp/script1.csv') }}"

            
