- name: Execute SQL command inside the container
  community.docker.docker_container_exec:
    container: my_container
    command: >
      /bin/bash -c '
      source /home/oracle/.bashrc &&
      ls -ltr /tmp &&
      export ORACLE_SID=ORCLCDB &&
      echo $ORACLE_SID &&
      export ORACLE_HOME=/opt/oracle/product/21c/dbhome_1 &&
      echo $ORACLE_HOME &&
      export PATH=$ORACLE_HOME/bin:$PATH &&
      echo $PATH &&
      sqlplus -s sys/Shan9871 as sysdba <<EOF
      select 1 from dual;
      select sysdate from dual;
      select name from v\$database;                   
      EOF
      '
  
