
---
- name: Run Docker container Oracle-DB
  hosts: webserver
  gather_facts: false
  become: yes
  tasks:  
    - name: Run Docker container  # Ensure this line is properly aligned
      docker_container:
        name: my_container
        image: us-central1-docker.pkg.dev/devops-project-1-419603/docker-images2/oracle/database:21.3.0-se2
        state: started 
      
    - name: Copy script file
      copy:
        src: /home/shandba90/script1.sh  # Local path to your script file
        dest: /home/shandba90/script1.sh  # Destination path on the new VM
        mode: "0755"  # Adjust permissions as needed    

    - name: "Copy the SQL file to the container and execute it "
      shell: "{{ item }}"
      register: command_output
      with_items:
        - sleep 90
        - sudo docker cp /home/shandba90/script1.sh my_container:/tmp/
        - sudo docker exec -it my_container bash -c "/tmp/script1.sh > /tmp/script1.html"
        - sudo docker exec -it my_container bash -c "cat /tmp/script1.html"
        - sudo docker exec -it my_container bash -c /tmp/script1.sh > /tmp/script1.html   
        - chmod 755 /tmp/script1.html
        - cat /tmp/script1.html

    - name: "Display command output"
      debug:
        msg: "{{ item.stdout }}"
      with_items: "{{ command_output.results }}" 

    - name: Fetch files
      fetch:
        src: /tmp/script1.html
        dest: /tmp/
        flat: yes  

    - name: "Display SQL*Plus output"
      debug:        
        msg: "{{ lookup('file', '/tmp/script1.html') }}"

            
